# 端口号
server:
  port: 8080

# spring配置
spring:
  application:
    name: Windfall
  # 配置数据库
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/windfall?characterEncoding=utf8&useSSL=false
    # 用户名要修改为自己的用户名
    username: root
    password: admin
    # 数据源类型
    type: com.alibaba.druid.pool.DruidDataSource
    # 显示sql语句
    jpa:
      dashow-sql: true
  # jackson序列化反序列化相关配置
  jackson:
    default-property-inclusion: NON_EMPTY
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

# 设置日志输出级别
logging:
  level:
    root: ERROR
    org:
      springframework:
        web: ERROR
      mybatis: ERROR
      planeswalker: DEBUG

# 开启Mybatis下划线命名转驼峰命名
mybatis:
  configuration:
    map-underscore-to-camel-case: true