# spring配置
spring:
  application:
    name: Windfall
  # 配置数据库
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db
    username: root
    password: root
  # 显示sql语句
  jpa:
    dashow-sql: true
  # h2 数据库 web 控制台配置
  h2:
    console:
      enabled: true
      path: /h2
  # jackson序列化反序列化相关配置
  jackson:
    default-property-inclusion: NON_EMPTY
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  # 视图不使用缓存，开发时关闭
  thymeleaf:
    cache: false
  redis:
    host: 172.17.91.23
    port: 6379
    maxTotal: 100
    maxIdle: 10
    maxWaitMillis: 100000
    timeout: 200
    password:

# 设置日志输出级别
logging:
  level:
    root: ERROR
    org:
      planeswalker: DEBUG

# 开启Mybatis下划线命名转驼峰命名
mybatis:
  configuration:
    map-underscore-to-camel-case: true