# 端口号
server:
  port: 8081

# 静态资源对外暴露的访问路径
# 文件上传目录（注意Linux和Windows上的目录结构不同）
# uploadFolder: classpath:/static/
file:
  staticAccessPath: /static/**
  # E:\\拾柒美妆\\
  uploadFolder: /Users/nanbei/Downloads/Beauty17/static/

# spring配置
spring:
  application:
    name: Beauty17
  # 配置数据库
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:beauty17
    username: root
    password: root
    # 配置数据库类型及脚本路径
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
    # sql 脚本编码
    sql-script-encoding: utf-8
  # 显示sql语句
  jpa:
    dashow-sql: true
    hibernate:
      # 每次运行程序，没有表格会新建表格，表内有数据不会清空，只会更新
      ddl-auto: update
  # h2 数据库 web 控制台配置
  h2:
    console:
      enabled: true
      path: /h2
  mvc:
    # 静态资源映射访问路径
    static-path-pattern: /**
  resources:
    # 静态资源所在目录
    static-locations: file:${file.uploadFolder},classpath:/static/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

# 设置日志输出级别
logging:
  level:
    root: ERROR
    org:
      springframework:
        web: ERROR
      mybatis: ERROR
      planeswalker: DEBUG

# 开启Mybatis下划线命名转驼峰命名
mybatis:
  configuration:
    map-underscore-to-camel-case: true