insert into user (user_id, user_name, password, email, create_time, update_time, state, authority) values ('root', '管理员', '1', 'root@qq.com', now(), now(), 1, 0);
insert into user (user_id, user_name, password, email, create_time, update_time, state, authority) values ('user', '普通用户', '1', 'user@qq.com', now(), now(), 1, 1);

insert into user_info (user_id, favourite, signature, create_time, update_time) values ('root', '彩妆，香水，护肤品', 'root的个性签名', now(), now());
insert into user_info (user_id, favourite, signature, create_time, update_time) values ('user', '彩妆', 'user的个性签名', now(), now());

insert into comment (comment_id, comment_pid, user_id, img_url, content, like_num, create_time, update_time, title) values ('rootComment0', '0', 'root', 'http://5b0988e595225.cdn.sohucs.com/images/20171025/153cea00c53d45f2a2d749c28cbf9a93.jpeg', 'root评测内容0', '0', now(), now(), '评测标题0');
insert into comment (comment_id, comment_pid, user_id, img_url, content, like_num, create_time, update_time, title) values ('rootComment1', '0', 'root', 'http://5b0988e595225.cdn.sohucs.com/images/20171025/153cea00c53d45f2a2d749c28cbf9a93.jpeg', 'root评测内容1', '0', now(), now(), '评测标题1');
insert into comment (comment_id, comment_pid, user_id, img_url, content, like_num, create_time, update_time, title) values ('rootComment2', '0', 'root', 'http://5b0988e595225.cdn.sohucs.com/images/20171025/153cea00c53d45f2a2d749c28cbf9a93.jpeg', 'root评测内容2', '0', now(), now(), '评测标题2');
insert into comment (comment_id, comment_pid, user_id, img_url, content, like_num, create_time, update_time, title) values ('rootComment3', '0', 'root', 'http://5b0988e595225.cdn.sohucs.com/images/20171025/153cea00c53d45f2a2d749c28cbf9a93.jpeg', 'root评测内容3', '0', now(), now(), '评测标题3');
insert into comment (comment_id, comment_pid, user_id, img_url, content, like_num, create_time, update_time, title) values ('rootComment4', '0', 'root', 'http://5b0988e595225.cdn.sohucs.com/images/20171025/153cea00c53d45f2a2d749c28cbf9a93.jpeg', 'root评测内容4', '0', now(), now(), '评测标题4');
insert into comment (comment_id, comment_pid, user_id, img_url, content, like_num, create_time, update_time, title) values ('rootComment5', '0', 'root', 'http://5b0988e595225.cdn.sohucs.com/images/20171025/153cea00c53d45f2a2d749c28cbf9a93.jpeg', 'root评测内容5', '0', now(), now(), '评测标题5');
insert into comment (comment_id, comment_pid, user_id, img_url, content, like_num, create_time, update_time, title) values ('rootComment6', '0', 'root', 'http://5b0988e595225.cdn.sohucs.com/images/20171025/153cea00c53d45f2a2d749c28cbf9a93.jpeg', 'root评测内容6', '0', now(), now(), '评测标题6');
insert into comment (comment_id, comment_pid, user_id, img_url, content, like_num, create_time, update_time, title) values ('rootComment7', '0', 'root', 'http://5b0988e595225.cdn.sohucs.com/images/20171025/153cea00c53d45f2a2d749c28cbf9a93.jpeg', 'root评测内容7', '0', now(), now(), '评测标题7');
insert into comment (comment_id, comment_pid, user_id, img_url, content, like_num, create_time, update_time, title) values ('rootComment8', '0', 'root', 'http://5b0988e595225.cdn.sohucs.com/images/20171025/153cea00c53d45f2a2d749c28cbf9a93.jpeg', 'root评测内容8', '0', now(), now(), '评测标题8');
insert into comment (comment_id, comment_pid, user_id, img_url, content, like_num, create_time, update_time, title) values ('rootComment9', '0', 'root', 'http://5b0988e595225.cdn.sohucs.com/images/20171025/153cea00c53d45f2a2d749c28cbf9a93.jpeg', 'root评测内容9', '0', now(), now(), '评测标题9');
insert into comment (comment_id, comment_pid, user_id, img_url, content, like_num, create_time, update_time, title) values ('rootComment10', '0', 'root', 'http://5b0988e595225.cdn.sohucs.com/images/20171025/153cea00c53d45f2a2d749c28cbf9a93.jpeg', 'root评测内容10', '0', now(), now(), '评测标题10');
insert into comment (comment_id, comment_pid, user_id, img_url, content, like_num, create_time, update_time, title) values ('rootComment11', 'rootComment0', 'root', null, 'root评测内容的留言', '0', now(), now(), '留言标题1');
insert into comment (comment_id, comment_pid, user_id, img_url, content, like_num, create_time, update_time, title) values ('rootComment12', 'rootComment0', 'root', null, 'root评测内容的留言', '0', now(), now(), '留言标题2');
insert into comment (comment_id, comment_pid, user_id, img_url, content, like_num, create_time, update_time, title) values ('rootComment13', 'rootComment0', 'root', null, 'root评测内容的留言', '0', now(), now(), '留言标题3');
insert into comment (comment_id, comment_pid, user_id, img_url, content, like_num, create_time, update_time, title) values ('rootComment14', 'rootComment0', 'root', null, 'root评测内容的留言', '0', now(), now(), '留言标题4');
insert into comment (comment_id, comment_pid, user_id, img_url, content, like_num, create_time, update_time, title) values ('rootComment15', 'rootComment0', 'root', null, 'root评测内容的留言', '0', now(), now(), '留言标题5');
insert into comment (comment_id, comment_pid, user_id, img_url, content, like_num, create_time, update_time, title) values ('rootComment16', 'rootComment0', 'root', null, 'root评测内容的留言', '0', now(), now(), '留言标题6');
insert into comment (comment_id, comment_pid, user_id, img_url, content, like_num, create_time, update_time, title) values ('rootComment17', 'rootComment0', 'root', null, 'root评测内容的留言', '0', now(), now(), '留言标题7');
insert into comment (comment_id, comment_pid, user_id, img_url, content, like_num, create_time, update_time, title) values ('rootComment18', 'rootComment0', 'root', null, 'root评测内容的留言', '0', now(), now(), '留言标题8');
insert into comment (comment_id, comment_pid, user_id, img_url, content, like_num, create_time, update_time, title) values ('rootComment19', 'rootComment0', 'root', null, 'root评测内容的留言', '0', now(), now(), '留言标题9');
insert into comment (comment_id, comment_pid, user_id, img_url, content, like_num, create_time, update_time, title) values ('rootComment20', 'rootComment0', 'root', null, 'root评测内容的留言', '0', now(), now(), '留言标题10');
insert into comment (comment_id, comment_pid, user_id, img_url, content, like_num, create_time, update_time, title) values ('rootComment21', 'rootComment0', 'root', null, 'root评测内容的留言', '0', now(), now(), '留言标题11');
insert into comment (comment_id, comment_pid, user_id, img_url, content, like_num, create_time, update_time, title) values ('rootComment22', 'rootComment0', 'root', null, 'root评测内容的留言', '0', now(), now(), '留言标题12');

insert into goods(goods_id, goods_name, brand, type, set, requirement, introduce, description, usage, img, tao_bao_url, price)
 values ('testGoods', '小仙贝唇膏', '欧莱雅', '彩妆' ,'XXB-001', '唇', '高级贝壳外壳 细腻闪耀唇色 一抹仙气贝出', '兼具唇釉的浓郁亮泽与唇膏的舒适易用，显色、滋润不黏腻。', '适量转出1-2mm膏体，均匀涂抹于唇部。', 'https://www.lorealparis.com.cn/Product/Detail/1231.loreal', 'https://detail.tmall.com/item.htm?spm=a1z10.1-b-s.w5003-21588119984.1.6a5f3654AuddrV&id=563367801510&skuId=4024837316337&scene=taobao_shop', 145.00);