# spring配置
spring:
  application:
    name: Windfall
  # 配置数据库
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:windfall
    username: root
    password: root
  # 显示sql语句
  jpa:
    dashow-sql: true
    hibernate:
      # 每次运行程序，没有表格会新建表格，表内有数据不会清空，只会更新
      ddl-auto: update
  # h2 数据库 web 控制台配置
  h2:
    console:
      enabled: true
      path: /h2
  # jackson序列化反序列化相关配置
  jackson:
    default-property-inclusion: NON_EMPTY
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  #邮件部分
  mail:
    host: smtp.qq.com
    username: yqzhu1528@foxmail.com
    #发送方的授权码
    password: xbrogbbyqnotbfje
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: ture
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
    # 修改发送邮件TCP端口
    port: 465

# 设置日志输出级别
logging:
  level:
    root: ERROR
    org:
      springframework:
        web: ERROR
      mybatis: ERROR
      planeswalker: DEBUG

# 开启Mybatis下划线命名转驼峰命名
mybatis:
  configuration:
    map-underscore-to-camel-case: true